/**
 * photos.js — Treehouse Events Image Configuration v6 FINAL
 * Every image on the site is a named constant here.
 * To swap any photo: change the path on one line and commit. No HTML editing required.
 */

// ── CORE ASSETS ───────────────────────────────────────────
const HERO_BG    = "/img/hero-new.jpg";     // Hero fallback background. Full crowd, One WTC, golden hour.
const HERO_VIDEO = "/img/hero-video.mp4";   // Hero background video. Autoplay, muted, loop. Fallback: HERO_BG.
const LOGO       = "/img/logo.png";          // Official wordmark. Always transparent PNG. Never replace with fonts.
const MAIN_PHOTO_1 = "/img/main-photo-1.jpg"; // Main site featured photo 1 — homepage/about section.
const MAIN_PHOTO_2 = "/img/main-photo-2.jpg"; // Main site featured photo 2 — homepage/gallery feature.
const MAIN_PHOTO_3 = "/img/main-photo-3.jpg"; // Main site featured photo 3 — homepage/gallery feature.

// ── PARTY 1: TRIBECA ROOFTOP ─────────────────────────────────
// pic-time: https://curtispan.pic-time.com/-treehouse_1018/gallery
const TRIBECA_01 = "/img/gallery/tribeca-rooftop/tribeca-001.jpg"; // Tribeca Rooftop photo 1
const TRIBECA_02 = "/img/gallery/tribeca-rooftop/tribeca-002.jpg"; // Tribeca Rooftop photo 2
const TRIBECA_03 = "/img/gallery/tribeca-rooftop/tribeca-003.jpg"; // Tribeca Rooftop photo 3
const TRIBECA_04 = "/img/gallery/tribeca-rooftop/tribeca-004.jpg"; // Tribeca Rooftop photo 4
const TRIBECA_05 = "/img/gallery/tribeca-rooftop/tribeca-005.jpg"; // Tribeca Rooftop photo 5
const TRIBECA_06 = "/img/gallery/tribeca-rooftop/tribeca-006.jpg"; // Tribeca Rooftop photo 6
const TRIBECA_07 = "/img/gallery/tribeca-rooftop/tribeca-007.jpg"; // Tribeca Rooftop photo 7
const TRIBECA_08 = "/img/gallery/tribeca-rooftop/tribeca-008.jpg"; // Tribeca Rooftop photo 8
const TRIBECA_09 = "/img/gallery/tribeca-rooftop/tribeca-009.jpg"; // Tribeca Rooftop photo 9
const TRIBECA_10 = "/img/gallery/tribeca-rooftop/tribeca-010.jpg"; // Tribeca Rooftop photo 10
const TRIBECA_11 = "/img/gallery/tribeca-rooftop/tribeca-011.jpg"; // Tribeca Rooftop photo 11
const TRIBECA_12 = "/img/gallery/tribeca-rooftop/tribeca-012.jpg"; // Tribeca Rooftop photo 12
const TRIBECA_13 = "/img/gallery/tribeca-rooftop/tribeca-013.jpg"; // Tribeca Rooftop photo 13
const TRIBECA_14 = "/img/gallery/tribeca-rooftop/tribeca-014.jpg"; // Tribeca Rooftop photo 14
const TRIBECA_15 = "/img/gallery/tribeca-rooftop/tribeca-015.jpg"; // Tribeca Rooftop photo 15
const TRIBECA_16 = "/img/gallery/tribeca-rooftop/tribeca-016.jpg"; // Tribeca Rooftop photo 16
const TRIBECA_17 = "/img/gallery/tribeca-rooftop/tribeca-017.jpg"; // Tribeca Rooftop photo 17
const TRIBECA_18 = "/img/gallery/tribeca-rooftop/tribeca-018.jpg"; // Tribeca Rooftop photo 18
const TRIBECA_19 = "/img/gallery/tribeca-rooftop/tribeca-019.jpg"; // Tribeca Rooftop photo 19
const TRIBECA_20 = "/img/gallery/tribeca-rooftop/tribeca-020.jpg"; // Tribeca Rooftop photo 20
const TRIBECA_21 = "/img/gallery/tribeca-rooftop/tribeca-021.jpg"; // Tribeca Rooftop photo 21
const TRIBECA_22 = "/img/gallery/tribeca-rooftop/tribeca-022.jpg"; // Tribeca Rooftop photo 22
const TRIBECA_23 = "/img/gallery/tribeca-rooftop/tribeca-023.jpg"; // Tribeca Rooftop photo 23
const TRIBECA_24 = "/img/gallery/tribeca-rooftop/tribeca-024.jpg"; // Tribeca Rooftop photo 24
const TRIBECA_25 = "/img/gallery/tribeca-rooftop/tribeca-025.jpg"; // Tribeca Rooftop photo 25
const TRIBECA_26 = "/img/gallery/tribeca-rooftop/tribeca-026.jpg"; // Tribeca Rooftop photo 26
const TRIBECA_27 = "/img/gallery/tribeca-rooftop/tribeca-027.jpg"; // Tribeca Rooftop photo 27
const TRIBECA_28 = "/img/gallery/tribeca-rooftop/tribeca-028.jpg"; // Tribeca Rooftop photo 28
const TRIBECA_29 = "/img/gallery/tribeca-rooftop/tribeca-029.jpg"; // Tribeca Rooftop photo 29
const TRIBECA_30 = "/img/gallery/tribeca-rooftop/tribeca-030.jpg"; // Tribeca Rooftop photo 30
const TRIBECA_31 = "/img/gallery/tribeca-rooftop/tribeca-031.jpg"; // Tribeca Rooftop photo 31
const TRIBECA_32 = "/img/gallery/tribeca-rooftop/tribeca-032.jpg"; // Tribeca Rooftop photo 32
const TRIBECA_33 = "/img/gallery/tribeca-rooftop/tribeca-033.jpg"; // Tribeca Rooftop photo 33
const TRIBECA_34 = "/img/gallery/tribeca-rooftop/tribeca-034.jpg"; // Tribeca Rooftop photo 34
const TRIBECA_35 = "/img/gallery/tribeca-rooftop/tribeca-035.jpg"; // Tribeca Rooftop photo 35
const TRIBECA_36 = "/img/gallery/tribeca-rooftop/tribeca-036.jpg"; // Tribeca Rooftop photo 36
const TRIBECA_37 = "/img/gallery/tribeca-rooftop/tribeca-037.jpg"; // Tribeca Rooftop photo 37
const TRIBECA_38 = "/img/gallery/tribeca-rooftop/tribeca-038.jpg"; // Tribeca Rooftop photo 38
const TRIBECA_39 = "/img/gallery/tribeca-rooftop/tribeca-039.jpg"; // Tribeca Rooftop photo 39
const TRIBECA_40 = "/img/gallery/tribeca-rooftop/tribeca-040.jpg"; // Tribeca Rooftop photo 40
const TRIBECA_41 = "/img/gallery/tribeca-rooftop/tribeca-041.jpg"; // Tribeca Rooftop photo 41
const TRIBECA_42 = "/img/gallery/tribeca-rooftop/tribeca-042.jpg"; // Tribeca Rooftop photo 42
const TRIBECA_43 = "/img/gallery/tribeca-rooftop/tribeca-043.jpg"; // Tribeca Rooftop photo 43
const TRIBECA_44 = "/img/gallery/tribeca-rooftop/tribeca-044.jpg"; // Tribeca Rooftop photo 44
const TRIBECA_45 = "/img/gallery/tribeca-rooftop/tribeca-045.jpg"; // Tribeca Rooftop photo 45
const TRIBECA_46 = "/img/gallery/tribeca-rooftop/tribeca-046.jpg"; // Tribeca Rooftop photo 46
const TRIBECA_47 = "/img/gallery/tribeca-rooftop/tribeca-047.jpg"; // Tribeca Rooftop photo 47
const TRIBECA_48 = "/img/gallery/tribeca-rooftop/tribeca-048.jpg"; // Tribeca Rooftop photo 48
const TRIBECA_49 = "/img/gallery/tribeca-rooftop/tribeca-049.jpg"; // Tribeca Rooftop photo 49
const TRIBECA_50 = "/img/gallery/tribeca-rooftop/tribeca-050.jpg"; // Tribeca Rooftop photo 50

// ── PARTY 2: SOHO SOIREE ─────────────────────────────────────
// pic-time: https://curtispan.pic-time.com/-treehouse0531/gallery
const SOHO_01 = "/img/gallery/soho-soiree/soho-001.jpg"; // SoHo Soiree photo 1
const SOHO_02 = "/img/gallery/soho-soiree/soho-002.jpg"; // SoHo Soiree photo 2
const SOHO_03 = "/img/gallery/soho-soiree/soho-003.jpg"; // SoHo Soiree photo 3
const SOHO_04 = "/img/gallery/soho-soiree/soho-004.jpg"; // SoHo Soiree photo 4
const SOHO_05 = "/img/gallery/soho-soiree/soho-005.jpg"; // SoHo Soiree photo 5
const SOHO_06 = "/img/gallery/soho-soiree/soho-006.jpg"; // SoHo Soiree photo 6
const SOHO_07 = "/img/gallery/soho-soiree/soho-007.jpg"; // SoHo Soiree photo 7
const SOHO_08 = "/img/gallery/soho-soiree/soho-008.jpg"; // SoHo Soiree photo 8
const SOHO_09 = "/img/gallery/soho-soiree/soho-009.jpg"; // SoHo Soiree photo 9
const SOHO_10 = "/img/gallery/soho-soiree/soho-010.jpg"; // SoHo Soiree photo 10
const SOHO_11 = "/img/gallery/soho-soiree/soho-011.jpg"; // SoHo Soiree photo 11
const SOHO_12 = "/img/gallery/soho-soiree/soho-012.jpg"; // SoHo Soiree photo 12
const SOHO_13 = "/img/gallery/soho-soiree/soho-013.jpg"; // SoHo Soiree photo 13
const SOHO_14 = "/img/gallery/soho-soiree/soho-014.jpg"; // SoHo Soiree photo 14
const SOHO_15 = "/img/gallery/soho-soiree/soho-015.jpg"; // SoHo Soiree photo 15
const SOHO_16 = "/img/gallery/soho-soiree/soho-016.jpg"; // SoHo Soiree photo 16
const SOHO_17 = "/img/gallery/soho-soiree/soho-017.jpg"; // SoHo Soiree photo 17
const SOHO_18 = "/img/gallery/soho-soiree/soho-018.jpg"; // SoHo Soiree photo 18
const SOHO_19 = "/img/gallery/soho-soiree/soho-019.jpg"; // SoHo Soiree photo 19
const SOHO_20 = "/img/gallery/soho-soiree/soho-020.jpg"; // SoHo Soiree photo 20
const SOHO_21 = "/img/gallery/soho-soiree/soho-021.jpg"; // SoHo Soiree photo 21
const SOHO_22 = "/img/gallery/soho-soiree/soho-022.jpg"; // SoHo Soiree photo 22
const SOHO_23 = "/img/gallery/soho-soiree/soho-023.jpg"; // SoHo Soiree photo 23
const SOHO_24 = "/img/gallery/soho-soiree/soho-024.jpg"; // SoHo Soiree photo 24
const SOHO_25 = "/img/gallery/soho-soiree/soho-025.jpg"; // SoHo Soiree photo 25
const SOHO_26 = "/img/gallery/soho-soiree/soho-026.jpg"; // SoHo Soiree photo 26
const SOHO_27 = "/img/gallery/soho-soiree/soho-027.jpg"; // SoHo Soiree photo 27
const SOHO_28 = "/img/gallery/soho-soiree/soho-028.jpg"; // SoHo Soiree photo 28
const SOHO_29 = "/img/gallery/soho-soiree/soho-029.jpg"; // SoHo Soiree photo 29
const SOHO_30 = "/img/gallery/soho-soiree/soho-030.jpg"; // SoHo Soiree photo 30
const SOHO_31 = "/img/gallery/soho-soiree/soho-031.jpg"; // SoHo Soiree photo 31
const SOHO_32 = "/img/gallery/soho-soiree/soho-032.jpg"; // SoHo Soiree photo 32
const SOHO_33 = "/img/gallery/soho-soiree/soho-033.jpg"; // SoHo Soiree photo 33
const SOHO_34 = "/img/gallery/soho-soiree/soho-034.jpg"; // SoHo Soiree photo 34
const SOHO_35 = "/img/gallery/soho-soiree/soho-035.jpg"; // SoHo Soiree photo 35
const SOHO_36 = "/img/gallery/soho-soiree/soho-036.jpg"; // SoHo Soiree photo 36
const SOHO_37 = "/img/gallery/soho-soiree/soho-037.jpg"; // SoHo Soiree photo 37
const SOHO_38 = "/img/gallery/soho-soiree/soho-038.jpg"; // SoHo Soiree photo 38
const SOHO_39 = "/img/gallery/soho-soiree/soho-039.jpg"; // SoHo Soiree photo 39
const SOHO_40 = "/img/gallery/soho-soiree/soho-040.jpg"; // SoHo Soiree photo 40
const SOHO_41 = "/img/gallery/soho-soiree/soho-041.jpg"; // SoHo Soiree photo 41
const SOHO_42 = "/img/gallery/soho-soiree/soho-042.jpg"; // SoHo Soiree photo 42
const SOHO_43 = "/img/gallery/soho-soiree/soho-043.jpg"; // SoHo Soiree photo 43
const SOHO_44 = "/img/gallery/soho-soiree/soho-044.jpg"; // SoHo Soiree photo 44
const SOHO_45 = "/img/gallery/soho-soiree/soho-045.jpg"; // SoHo Soiree photo 45
const SOHO_46 = "/img/gallery/soho-soiree/soho-046.jpg"; // SoHo Soiree photo 46
const SOHO_47 = "/img/gallery/soho-soiree/soho-047.jpg"; // SoHo Soiree photo 47
const SOHO_48 = "/img/gallery/soho-soiree/soho-048.jpg"; // SoHo Soiree photo 48
const SOHO_49 = "/img/gallery/soho-soiree/soho-049.jpg"; // SoHo Soiree photo 49
const SOHO_50 = "/img/gallery/soho-soiree/soho-050.jpg"; // SoHo Soiree photo 50

// ── PARTY 3: CHRISTMAS IN NYC ───────────────────────────────────
// pic-time: https://curtispan.pic-time.com/-treehouse1212/gallery
const XMAS_01 = "/img/gallery/christmas-nyc/xmas-001.jpg"; // Christmas in NYC photo 1
const XMAS_02 = "/img/gallery/christmas-nyc/xmas-002.jpg"; // Christmas in NYC photo 2
const XMAS_03 = "/img/gallery/christmas-nyc/xmas-003.jpg"; // Christmas in NYC photo 3
const XMAS_04 = "/img/gallery/christmas-nyc/xmas-004.jpg"; // Christmas in NYC photo 4
const XMAS_05 = "/img/gallery/christmas-nyc/xmas-005.jpg"; // Christmas in NYC photo 5
const XMAS_06 = "/img/gallery/christmas-nyc/xmas-006.jpg"; // Christmas in NYC photo 6
const XMAS_07 = "/img/gallery/christmas-nyc/xmas-007.jpg"; // Christmas in NYC photo 7
const XMAS_08 = "/img/gallery/christmas-nyc/xmas-008.jpg"; // Christmas in NYC photo 8
const XMAS_09 = "/img/gallery/christmas-nyc/xmas-009.jpg"; // Christmas in NYC photo 9
const XMAS_10 = "/img/gallery/christmas-nyc/xmas-010.jpg"; // Christmas in NYC photo 10
const XMAS_11 = "/img/gallery/christmas-nyc/xmas-011.jpg"; // Christmas in NYC photo 11
const XMAS_12 = "/img/gallery/christmas-nyc/xmas-012.jpg"; // Christmas in NYC photo 12
const XMAS_13 = "/img/gallery/christmas-nyc/xmas-013.jpg"; // Christmas in NYC photo 13
const XMAS_14 = "/img/gallery/christmas-nyc/xmas-014.jpg"; // Christmas in NYC photo 14
const XMAS_15 = "/img/gallery/christmas-nyc/xmas-015.jpg"; // Christmas in NYC photo 15
const XMAS_16 = "/img/gallery/christmas-nyc/xmas-016.jpg"; // Christmas in NYC photo 16
const XMAS_17 = "/img/gallery/christmas-nyc/xmas-017.jpg"; // Christmas in NYC photo 17
const XMAS_18 = "/img/gallery/christmas-nyc/xmas-018.jpg"; // Christmas in NYC photo 18
const XMAS_19 = "/img/gallery/christmas-nyc/xmas-019.jpg"; // Christmas in NYC photo 19
const XMAS_20 = "/img/gallery/christmas-nyc/xmas-020.jpg"; // Christmas in NYC photo 20
const XMAS_21 = "/img/gallery/christmas-nyc/xmas-021.jpg"; // Christmas in NYC photo 21
const XMAS_22 = "/img/gallery/christmas-nyc/xmas-022.jpg"; // Christmas in NYC photo 22
const XMAS_23 = "/img/gallery/christmas-nyc/xmas-023.jpg"; // Christmas in NYC photo 23
const XMAS_24 = "/img/gallery/christmas-nyc/xmas-024.jpg"; // Christmas in NYC photo 24
const XMAS_25 = "/img/gallery/christmas-nyc/xmas-025.jpg"; // Christmas in NYC photo 25
const XMAS_26 = "/img/gallery/christmas-nyc/xmas-026.jpg"; // Christmas in NYC photo 26
const XMAS_27 = "/img/gallery/christmas-nyc/xmas-027.jpg"; // Christmas in NYC photo 27
const XMAS_28 = "/img/gallery/christmas-nyc/xmas-028.jpg"; // Christmas in NYC photo 28
const XMAS_29 = "/img/gallery/christmas-nyc/xmas-029.jpg"; // Christmas in NYC photo 29
const XMAS_30 = "/img/gallery/christmas-nyc/xmas-030.jpg"; // Christmas in NYC photo 30
const XMAS_31 = "/img/gallery/christmas-nyc/xmas-031.jpg"; // Christmas in NYC photo 31
const XMAS_32 = "/img/gallery/christmas-nyc/xmas-032.jpg"; // Christmas in NYC photo 32
const XMAS_33 = "/img/gallery/christmas-nyc/xmas-033.jpg"; // Christmas in NYC photo 33
const XMAS_34 = "/img/gallery/christmas-nyc/xmas-034.jpg"; // Christmas in NYC photo 34
const XMAS_35 = "/img/gallery/christmas-nyc/xmas-035.jpg"; // Christmas in NYC photo 35
const XMAS_36 = "/img/gallery/christmas-nyc/xmas-036.jpg"; // Christmas in NYC photo 36
const XMAS_37 = "/img/gallery/christmas-nyc/xmas-037.jpg"; // Christmas in NYC photo 37
const XMAS_38 = "/img/gallery/christmas-nyc/xmas-038.jpg"; // Christmas in NYC photo 38
const XMAS_39 = "/img/gallery/christmas-nyc/xmas-039.jpg"; // Christmas in NYC photo 39
const XMAS_40 = "/img/gallery/christmas-nyc/xmas-040.jpg"; // Christmas in NYC photo 40
const XMAS_41 = "/img/gallery/christmas-nyc/xmas-041.jpg"; // Christmas in NYC photo 41
const XMAS_42 = "/img/gallery/christmas-nyc/xmas-042.jpg"; // Christmas in NYC photo 42
const XMAS_43 = "/img/gallery/christmas-nyc/xmas-043.jpg"; // Christmas in NYC photo 43
const XMAS_44 = "/img/gallery/christmas-nyc/xmas-044.jpg"; // Christmas in NYC photo 44
const XMAS_45 = "/img/gallery/christmas-nyc/xmas-045.jpg"; // Christmas in NYC photo 45
const XMAS_46 = "/img/gallery/christmas-nyc/xmas-046.jpg"; // Christmas in NYC photo 46
const XMAS_47 = "/img/gallery/christmas-nyc/xmas-047.jpg"; // Christmas in NYC photo 47
const XMAS_48 = "/img/gallery/christmas-nyc/xmas-048.jpg"; // Christmas in NYC photo 48

// ── PARTY 4: DINNER PARTIES ─────────────────────────────────
// No pic-time gallery — no button on this section
const DINNER_01 = "/img/gallery/dinner-parties/dinner-001.jpg"; // Dinner Parties photo 1
const DINNER_02 = "/img/gallery/dinner-parties/dinner-002.jpg"; // Dinner Parties photo 2
const DINNER_03 = "/img/gallery/dinner-parties/dinner-003.jpg"; // Dinner Parties photo 3
const DINNER_04 = "/img/gallery/dinner-parties/dinner-004.jpg"; // Dinner Parties photo 4
const DINNER_05 = "/img/gallery/dinner-parties/dinner-005.jpg"; // Dinner Parties photo 5
const DINNER_06 = "/img/gallery/dinner-parties/dinner-006.jpg"; // Dinner Parties photo 6
const DINNER_07 = "/img/gallery/dinner-parties/dinner-007.jpg"; // Dinner Parties photo 7
const DINNER_08 = "/img/gallery/dinner-parties/dinner-008.jpg"; // Dinner Parties photo 8
const DINNER_09 = "/img/gallery/dinner-parties/dinner-009.jpg"; // Dinner Parties photo 9
const DINNER_10 = "/img/gallery/dinner-parties/dinner-010.jpg"; // Dinner Parties photo 10
const DINNER_11 = "/img/gallery/dinner-parties/dinner-011.jpg"; // Dinner Parties photo 11
const DINNER_12 = "/img/gallery/dinner-parties/dinner-012.jpg"; // Dinner Parties photo 12
const DINNER_13 = "/img/gallery/dinner-parties/dinner-013.jpg"; // Dinner Parties photo 13
const DINNER_14 = "/img/gallery/dinner-parties/dinner-014.jpg"; // Dinner Parties photo 14
const DINNER_15 = "/img/gallery/dinner-parties/dinner-015.jpg"; // Dinner Parties photo 15
const DINNER_16 = "/img/gallery/dinner-parties/dinner-016.jpg"; // Dinner Parties photo 16
const DINNER_17 = "/img/gallery/dinner-parties/dinner-017.jpg"; // Dinner Parties photo 17
const DINNER_18 = "/img/gallery/dinner-parties/dinner-018.jpg"; // Dinner Parties photo 18
const DINNER_19 = "/img/gallery/dinner-parties/dinner-019.jpg"; // Dinner Parties photo 19
const DINNER_20 = "/img/gallery/dinner-parties/dinner-020.jpg"; // Dinner Parties photo 20
const DINNER_21 = "/img/gallery/dinner-parties/dinner-021.jpg"; // Dinner Parties photo 21
const DINNER_22 = "/img/gallery/dinner-parties/dinner-022.jpg"; // Dinner Parties photo 22
const DINNER_23 = "/img/gallery/dinner-parties/dinner-023.jpg"; // Dinner Parties photo 23
const DINNER_24 = "/img/gallery/dinner-parties/dinner-024.jpg"; // Dinner Parties photo 24
const DINNER_25 = "/img/gallery/dinner-parties/dinner-025.jpg"; // Dinner Parties photo 25
const DINNER_26 = "/img/gallery/dinner-parties/dinner-026.jpg"; // Dinner Parties photo 26
const DINNER_27 = "/img/gallery/dinner-parties/dinner-027.jpg"; // Dinner Parties photo 27
const DINNER_28 = "/img/gallery/dinner-parties/dinner-028.jpg"; // Dinner Parties photo 28
const DINNER_29 = "/img/gallery/dinner-parties/dinner-029.jpg"; // Dinner Parties photo 29
const DINNER_30 = "/img/gallery/dinner-parties/dinner-030.jpg"; // Dinner Parties photo 30
const DINNER_31 = "/img/gallery/dinner-parties/dinner-031.jpg"; // Dinner Parties photo 31

// ── PARTY 5: KNOX DAY ───────────────────────────────────────
// No pic-time gallery — no button on this section
const KNOX_01 = "/img/gallery/knox-day/knox-001.jpg"; // Knox Day photo 1
const KNOX_02 = "/img/gallery/knox-day/knox-002.jpg"; // Knox Day photo 2
const KNOX_03 = "/img/gallery/knox-day/knox-003.jpg"; // Knox Day photo 3
const KNOX_04 = "/img/gallery/knox-day/knox-004.jpg"; // Knox Day photo 4
const KNOX_05 = "/img/gallery/knox-day/knox-005.jpg"; // Knox Day photo 5
const KNOX_06 = "/img/gallery/knox-day/knox-006.jpg"; // Knox Day photo 6
const KNOX_07 = "/img/gallery/knox-day/knox-007.jpg"; // Knox Day photo 7
const KNOX_08 = "/img/gallery/knox-day/knox-008.jpg"; // Knox Day photo 8
const KNOX_09 = "/img/gallery/knox-day/knox-009.jpg"; // Knox Day photo 9
const KNOX_10 = "/img/gallery/knox-day/knox-010.jpg"; // Knox Day photo 10
const KNOX_11 = "/img/gallery/knox-day/knox-011.jpg"; // Knox Day photo 11
const KNOX_12 = "/img/gallery/knox-day/knox-012.jpg"; // Knox Day photo 12
const KNOX_13 = "/img/gallery/knox-day/knox-013.jpg"; // Knox Day photo 13
const KNOX_14 = "/img/gallery/knox-day/knox-014.jpg"; // Knox Day photo 14
const KNOX_15 = "/img/gallery/knox-day/knox-015.jpg"; // Knox Day photo 15
const KNOX_16 = "/img/gallery/knox-day/knox-016.jpg"; // Knox Day photo 16
const KNOX_17 = "/img/gallery/knox-day/knox-017.jpg"; // Knox Day photo 17
const KNOX_18 = "/img/gallery/knox-day/knox-018.jpg"; // Knox Day photo 18
const KNOX_19 = "/img/gallery/knox-day/knox-019.jpg"; // Knox Day photo 19
const KNOX_20 = "/img/gallery/knox-day/knox-020.jpg"; // Knox Day photo 20

// ── PARTY 6: WEST VILLAGE ──────────────────────────────────
// No pic-time gallery — no button on this section
const WESTVILLAGE_01 = "/img/gallery/west-village/westvillage-001.jpg"; // West Village photo 1
const WESTVILLAGE_02 = "/img/gallery/west-village/westvillage-002.jpg"; // West Village photo 2
const WESTVILLAGE_03 = "/img/gallery/west-village/westvillage-003.jpg"; // West Village photo 3
const WESTVILLAGE_04 = "/img/gallery/west-village/westvillage-004.jpg"; // West Village photo 4
const WESTVILLAGE_05 = "/img/gallery/west-village/westvillage-005.jpg"; // West Village photo 5
const WESTVILLAGE_06 = "/img/gallery/west-village/westvillage-006.jpg"; // West Village photo 6
const WESTVILLAGE_07 = "/img/gallery/west-village/westvillage-007.jpg"; // West Village photo 7
const WESTVILLAGE_08 = "/img/gallery/west-village/westvillage-008.jpg"; // West Village photo 8
const WESTVILLAGE_09 = "/img/gallery/west-village/westvillage-009.jpg"; // West Village photo 9
const WESTVILLAGE_10 = "/img/gallery/west-village/westvillage-010.jpg"; // West Village photo 10
const WESTVILLAGE_11 = "/img/gallery/west-village/westvillage-011.jpg"; // West Village photo 11
const WESTVILLAGE_12 = "/img/gallery/west-village/westvillage-012.jpg"; // West Village photo 12
const WESTVILLAGE_13 = "/img/gallery/west-village/westvillage-013.jpg"; // West Village photo 13
const WESTVILLAGE_14 = "/img/gallery/west-village/westvillage-014.jpg"; // West Village photo 14
const WESTVILLAGE_15 = "/img/gallery/west-village/westvillage-015.jpg"; // West Village photo 15
const WESTVILLAGE_16 = "/img/gallery/west-village/westvillage-016.jpg"; // West Village photo 16
const WESTVILLAGE_17 = "/img/gallery/west-village/westvillage-017.jpg"; // West Village photo 17
const WESTVILLAGE_18 = "/img/gallery/west-village/westvillage-018.jpg"; // West Village photo 18
const WESTVILLAGE_19 = "/img/gallery/west-village/westvillage-019.jpg"; // West Village photo 19
const WESTVILLAGE_20 = "/img/gallery/west-village/westvillage-020.jpg"; // West Village photo 20
const WESTVILLAGE_21 = "/img/gallery/west-village/westvillage-021.jpg"; // West Village photo 21
const WESTVILLAGE_22 = "/img/gallery/west-village/westvillage-022.jpg"; // West Village photo 22
const WESTVILLAGE_23 = "/img/gallery/west-village/westvillage-023.jpg"; // West Village photo 23
const WESTVILLAGE_24 = "/img/gallery/west-village/westvillage-024.jpg"; // West Village photo 24
const WESTVILLAGE_25 = "/img/gallery/west-village/westvillage-025.jpg"; // West Village photo 25
const WESTVILLAGE_26 = "/img/gallery/west-village/westvillage-026.jpg"; // West Village photo 26
const WESTVILLAGE_27 = "/img/gallery/west-village/westvillage-027.jpg"; // West Village photo 27
const WESTVILLAGE_28 = "/img/gallery/west-village/westvillage-028.jpg"; // West Village photo 28
const WESTVILLAGE_29 = "/img/gallery/west-village/westvillage-029.jpg"; // West Village photo 29
const WESTVILLAGE_30 = "/img/gallery/west-village/westvillage-030.jpg"; // West Village photo 30
const WESTVILLAGE_31 = "/img/gallery/west-village/westvillage-031.jpg"; // West Village photo 31
const WESTVILLAGE_32 = "/img/gallery/west-village/westvillage-032.jpg"; // West Village photo 32
const WESTVILLAGE_33 = "/img/gallery/west-village/westvillage-033.jpg"; // West Village photo 33
const WESTVILLAGE_34 = "/img/gallery/west-village/westvillage-034.jpg"; // West Village photo 34
const WESTVILLAGE_35 = "/img/gallery/west-village/westvillage-035.jpg"; // West Village photo 35
const WESTVILLAGE_36 = "/img/gallery/west-village/westvillage-036.jpg"; // West Village photo 36
const WESTVILLAGE_37 = "/img/gallery/west-village/westvillage-037.jpg"; // West Village photo 37
const WESTVILLAGE_38 = "/img/gallery/west-village/westvillage-038.jpg"; // West Village photo 38
const WESTVILLAGE_39 = "/img/gallery/west-village/westvillage-039.jpg"; // West Village photo 39
const WESTVILLAGE_40 = "/img/gallery/west-village/westvillage-040.jpg"; // West Village photo 40
const WESTVILLAGE_41 = "/img/gallery/west-village/westvillage-041.jpg"; // West Village photo 41
const WESTVILLAGE_42 = "/img/gallery/west-village/westvillage-042.jpg"; // West Village photo 42
const WESTVILLAGE_43 = "/img/gallery/west-village/westvillage-043.jpg"; // West Village photo 43
const WESTVILLAGE_44 = "/img/gallery/west-village/westvillage-044.jpg"; // West Village photo 44
const WESTVILLAGE_45 = "/img/gallery/west-village/westvillage-045.jpg"; // West Village photo 45
const WESTVILLAGE_46 = "/img/gallery/west-village/westvillage-046.jpg"; // West Village photo 46
const WESTVILLAGE_47 = "/img/gallery/west-village/westvillage-047.jpg"; // West Village photo 47
const WESTVILLAGE_48 = "/img/gallery/west-village/westvillage-048.jpg"; // West Village photo 48
const WESTVILLAGE_49 = "/img/gallery/west-village/westvillage-049.jpg"; // West Village photo 49
const WESTVILLAGE_50 = "/img/gallery/west-village/westvillage-050.jpg"; // West Village photo 50
